# Generated by Django 5.2 on 2025-07-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('camisa', 'Camisa'), ('pantalon', 'Pantalón'), ('zapato', 'Zapato'), ('accesorio', 'Accesorio')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='garments/')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='outfits/')),
                ('garments', models.ManyToManyField(to='closet.garment')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('garments', models.ManyToManyField(blank=True, to='closet.garment')),
                ('outfits', models.ManyToManyField(blank=True, to='closet.outfit')),
            ],
        ),
    ]
