# Generated by Django 5.2 on 2025-07-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
