# Generated by Django 5.2 on 2025-11-11 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_folder_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='garment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='garments',
            field=models.ManyToManyField(blank=True, related_name='folders', to='closet.garment'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='outfits',
            field=models.ManyToManyField(blank=True, related_name='folders', to='closet.outfit'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='garments',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='closet.garment'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='garment',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='outfit',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='garment',
            index=models.Index(fields=['owner', 'category'], name='closet_garm_owner_i_e5e786_idx'),
        ),
    ]
