# Generated by Django 5.2 on 2025-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_alter_folder_options_alter_garment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='category',
            field=models.CharField(choices=[('salir', 'Salir'), ('cena', 'Ir a cenar'), ('fiesta_elegante', 'Fiesta elegante'), ('fiesta_elegante_sport', 'Fiesta elegante sport'), ('trabajo', 'Trabajo'), ('oficina', 'Oficina'), ('cita', 'Cita'), ('playa', 'Playa'), ('evento_formal', 'Evento formal'), ('casual', 'Casual / Diario')], default='casual', max_length=30),
        ),
    ]
