# Generated by Django 5.2 on 2025-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_outfit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('pantalon', 'Pantalón'), ('zapato', 'Zapato'), ('accesorio', 'Accesorio'), ('vestido', 'Vestido'), ('pollera', 'Pollera'), ('remera', 'Remera'), ('shorts', 'Shorts'), ('buzo', 'Buzo'), ('top', 'Top'), ('zapatilla', 'Zapatilla'), ('botas', 'Botas'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
